# Basic configuration
baseurl: https://atsign.dev/
canonifyURLs: false
disableAliases: true
disableHugoGeneratorInject: true
enableEmoji: true
enableGitInfo: false
enableRobotsTXT: true
languageCode: en_US
paginate: 7
rssLimit: 10

defaultContentLanguage: en

# Sitemap Config
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

taxonomies:
# TODO

# Relative Permalinks
# permalinks:
#   blog: /blog/:title/

minify:
  tdewolff:
    html:
      keepWhitespace: false

# Import doks theme modules
module:
  mounts:
    # ASSETS
    - source: assets
      target: assets
    - source: node_modules/@hyas/doks/assets
      target: assets
      excludeFiles:
        - scss/app.scss
        - scss/common/_dark.scss
        - scss/common/_variables.scss
        - scss/common/_fonts.scss
        - js/highlight.js
    - source: node_modules/font-awesome/scss
      target: assets/scss/font-awesome

    # vendor assets
    - source: node_modules/flexsearch
      target: assets/js/vendor/flexsearch
    - source: node_modules/katex
      target: assets/js/vendor/katex

    # STATIC
    - source: node_modules/font-awesome/fonts
      target: static/webfonts/font-awesome
    - source: static
      target: static

    # LAYOUTS
    - source: node_modules/@hyas/doks/layouts
      target: layouts
      excludeFiles:
        - docs/list.html
        - docs/single.html
        - partials/main/docs-navigation.html
        - partials/sidebar/auto-collapsible-menu.html
        - partials/head/resource-hints.html
        - index.html
    - source: layouts
      target: layouts

    # OTHER
    - source: content
      target: content
    - source: archetypes
      target: archetypes
    - source: data
      target: data
