mounts:
  # ASSETS
  - source: assets
    target: assets
  - source: node_modules/@hyas/doks/assets
    target: assets
    excludeFiles:
      - scss/app.scss
      - scss/common/_dark.scss
      - scss/common/_variables.scss
      - scss/common/_fonts.scss
      - scss/common/_global.scss
      - js/highlight.js
      - js/mermaid.js
  - source: node_modules/font-awesome/scss
    target: assets/scss/font-awesome

  # vendor assets
  - source: node_modules/flexsearch
    target: assets/js/vendor/flexsearch
  - source: node_modules/katex
    target: assets/js/vendor/katex

  # STATIC
  - source: node_modules/font-awesome/fonts
    target: static/webfonts/font-awesome
  - source: static
    target: static

  # LAYOUTS
  - source: node_modules/@hyas/doks/layouts
    target: layouts
    excludeFiles:
      - docs/list.html
      - docs/single.html
      - partials/main/docs-navigation.html
      - partials/sidebar/auto-collapsible-menu.html
      - partials/head/resource-hints.html
      - index.html
      - _default/list.html
      - _default/single.html
  - source: layouts
    target: layouts
    excludeFiles:
      - partials/sidebar/auto-collapsible-menu.html

  # OTHER
  - source: content/docs
    target: content
  - source: archetypes
    target: archetypes
  - source: layouts_docs
    target: layouts